# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('message', models.TextField(verbose_name='\u5185\u5bb9')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Category', verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
        ),
    ]
