# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4e66\u7c4d',
                'verbose_name_plural': '\u4e66\u7c4d',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5206\u7c7b\u4fe1\u606f', 'verbose_name_plural': '\u5206\u7c7b\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='book',
            field=models.ManyToManyField(to='form.Book', verbose_name='\u559c\u6b22\u7684\u4e66\u7c4d'),
        ),
    ]
